/run/verbose 1
#/tracking/verbose 1
/analysis/setOutputFileName GraphiteTargetBERTModelBeamSim.root
/run/initialize
/generator/setGenerator gps
/gps/particle proton
/gps/ene/type Mono
/gps/ene/mono 800. MeV
/gps/pos/type Beam
#/gps/pos/shape Rectangle
/gps/pos/centre -3.601 0. 0. m
/gps/pos/halfx 1.0 cm
/gps/pos/halfy 1.0 cm
/gps/pos/sigma_x 4.5 cm
/gps/pos/sigma_y 4.5 cm
#/gps/ang/type focused
/gps/pos/rot1 0. 0. 1.
/gps/direction 1. 0. 0.
/run/beamOn 10000
 