/run/verbose 1
/tracking/verbose 1
/analysis/setOutputFileName testPhot.root
/run/initialize
/generator/setGenerator gps
/gps/particle e-
#/gps/ion 18 40 0 0 
/gps/ene/type Mono
/gps/ene/mono 10. keV
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 26.0 0. 0. m
/gps/pos/halfx 1.0 cm
/gps/pos/halfy 1.0 cm
/gps/pos/sigma_x 4.5 cm
/gps/pos/sigma_y 4.5 cm
#/gps/ang/type focused
/gps/pos/rot1 0. 0. 1.
/gps/direction 1. 0. 0.
/run/beamOn 1
 